config/routes.rb
Rails.application.routes.draw do
  root to: 'sections#index'
  resources :sections do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section

  validates :name, :presence => true
  validates :content, :presence => true
  validates :order, :presence => true
  validates :section_id, presence: true

  def next
    tmpOrder = self.order + 1
    tmpSection = self.section_id
    foundLesson = Lesson.find_by(order: tmpOrder, section_id: tmpSection)
    if (foundLesson != nil)
      return foundLesson.id
    else
      return self.id
    end
  end

  def prev
    tmpOrder = self.order - 1
    tmpSection = self.section_id
    foundLesson = Lesson.find_by(order: tmpOrder, section_id: tmpSection)
    if (foundLesson != nil)
      return foundLesson.id
    else
      return self.id
    end
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons

  validates :title, :presence => true
  validates :order, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def new
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      flash[:notice] = "Lesson successfully added!"
      redirect_to section_path(@lesson.section)
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  def update
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      flash[:notice] = "Lesson successfully updated!"
      redirect_to section_path(@lesson.section)
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    flash[:notice] = "lesson destroyed!"
    redirect_to section_path(@lesson.section)
  end

  def show
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  private
  def lesson_params
    params.require(:lesson).permit(:name, :content, :order)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnToProgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1 class="jumbotron">Epicodus</h1>
      <%= yield %>
      <p><%= link_to "Return Home", sections_path %></p>
    </div>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= render('layouts/errors', :object => @lesson) %>

<%= form_for [@section, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br><br>
  <%= f.label :order %>
  <%= f.number_field :order %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit Lesson for <%= @section.title %></h1>

<%= render 'form' %>

app/views/lessons/new.html.erb
<h1>New lesson for <%= @section.title %></h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<div id="crouton">
  <ul class="lesson-nav">
    <li> <%= link_to "Previous", section_lesson_path(@section.id, @lesson.prev ) %> </li>
    <li> <%= link_to "Next", section_lesson_path(@section.id, @lesson.next ) %> </li>
  </ul>
</div>
<br>
<br>

<h3> <%= @section.title %> </h3>
<br>
<h3> <%= @lesson.name %> </h3>
<p> <%= @lesson.content %> </p>

app/views/sections/index.html.erb
<h3>Rails</h3>


<% @sections.each do |section| %>
  <ul>
    <li><%= link_to section.title, section_path(section) %> </li>
    <% section.lessons.each do |lesson|  %>
      <p> <%= link_to lesson.name, section_lesson_path(section.id, lesson.id) %> </p>
    <% end %>
  </ul>
<% end %>

app/views/sections/show.html.erb
<h3><%= @section.title %></h3>

<% if @section.lessons.any? %>

  <ul>
    <% @section.lessons.each do |lesson| %>
      <li>
        <%= lesson.name %> |
        <%= lesson.content %> |
        <%= lesson.order %> |
        <%= link_to "Edit", edit_section_lesson_path(@section, lesson) %> |
        <%= link_to "Delete", section_lesson_path(@section, lesson),
                                  :data => { :method => "delete" } %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no lessons yet!</p>
<% end %>

<p><%= link_to "Add a lesson", new_section_lesson_path(@section) %></p>